### PR TITLE
Swagger configuration added (ticket 120)

### PR DESCRIPTION
**Pull request by Pmahindra93**
- Swagger configuration added based on example provided by Professor
- Latest version of python dot env added to the file

### CODE REVIEW

**Review by shihokuni — CHANGES_REQUESTED** [review]
In **routes.py**

* Need to import below. (I think currently you can see "not defined" at line 42 `API`, also Travis log said `NameError: name 'Api' is not defined`)
`from flask_restx import Api, Resource, fields, reqparse, inputs`

* in the `promotion_model = ` at the line 72, I think not `_id` but `id` 

* query string arguments, we don't have `start_date` query. 

* When we do not implement Authorize, `authorizations=authorizations,` may not need at line 49

**Comment by shihokuni** [comment]
* `create_model = **api.model('Pet',`
-> not Pet 😄 

* the travis error log said
```
 File "/home/travis/build/nyu-devops-2021-summer-promotions/promotions/service/routes.py", line 52, in <module>
    authorizations=authorizations,
NameError: name 'authorizations' is not defined
```

I think we can remove the below and if we need it, let's try to add it.
`authorizations=authorizations,`

* we use `id` field not `'_id': fields.String` I think.

**Comment by shihokuni** [comment]
Travis passed!! Thank you !!!

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/fb67b460-e0db-4e33-aea8-c6c52f1e08e6 "nyu-promotion-service-sum21") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-dev-20210805-201509 "deploy-ibm-yp-us-south-promotions-dev-20210805-201509") to [dev](https://console.bluemix.net/apps/7e898312-2f36-4f7f-b420-ae7e094981ce?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:dev"), including commit c42b4aca3fa4be1f35d646e3b12c735cc0802680

**Comment by jtsen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/12847f01-db08-4f28-a98c-cc3e34de22cc?env_id=ibm:yp:us-south "nyu-promotion-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/fb67b460-e0db-4e33-aea8-c6c52f1e08e6 "nyu-promotion-service-sum21") deployed [promotions](https://github.com/nyu-devops-2021-summer-promotions/promotions/releases/tag/deploy-ibm-yp-us-south-promotions-prod-20210807-162945 "deploy-ibm-yp-us-south-promotions-prod-20210807-162945") to [prod](https://console.bluemix.net/apps/b60cc3cc-1522-45d8-84c0-fde436d5ba0a?env_id=ibm:yp:us-south "ibm:yp:us-south:promotions:prod"), including commit c42b4aca3fa4be1f35d646e3b12c735cc0802680

**Pull request merged**
