### PR TITLE
Update travis.yml

### PR DESCRIPTION
**Pull request by Pmahindra93**
- Codecov added to travis file

### CODE REVIEW

**Comment by shihokuni** [comment]
@Pmahindra93 This pull request is connecting to #49, right?

**Comment by Pmahindra93** [comment]
Yes, it is to add code cov to the repo (49)

**Comment by shihokuni** [comment]
Thank you! I did "connect issue"

**Comment by shihokuni** [comment]
> Yes, it is to add code cov to the repo (49)

Thank you! I did "connect issue"

**Pull request merged**
